New mechanism for automatic version number, based on git
If git is not available, it uses the version from the change log.
If git is available, it uses the current tag if the HEAD is tagged
and the repository is clean.  Else it uses the tag as the version
and the commit as the suffix, also mentioning whether the work
dir was clean at the time of the build.

Also moved the change log to standard name Changes

Also removed the makefile code that would install symlinks per
OpenGL command, since the new CmdlineGL.lib is a much better design.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -13,12 +13,16 @@ infodir = $(prefix)/info
 
 DEF_CC_CMD=${CC} ${CFLAGS} ${CPPFLAGS} `sdl-config --cflags`
 
-INSTALL_SHELL_BINDINGS=@INST_SHELL_BIND@
-
 ALL_HEADERS=*.h
 OBJ_FILES=SymbolHash.o Server.o ProcessInput.o ParseGL.o Global.o Contained_RBTree.o IntConstHash.autogen.o CmdHash.autogen.o HashFunc.o ImageLoader.o Font.o Version.o
 
 all: build
+
+$(OBJ_FILES): Makefile
+
+Makefile: Makefile.in
+	@echo Makefile is out of date, regenerating Makefile from Makefile.in
+	if [ -f ./config.status ]; then ./config.status; else ./configure; fi
 
 build: bin/CmdlineGL
 
@@ -27,12 +31,6 @@ bin/CmdlineGL: ${OBJ_FILES}
 	$(CC) $(CFLAGS) -o bin/CmdlineGL $(OBJ_FILES) $(LDFLAGS) `sdl-config --libs` $(LIBS)
 # I now strip the thing by default.  It knocks off about 350K on my system, lol.  Yay for staticly-compiled hash tables.
 	strip bin/CmdlineGL
-# subsequent builds are tagged by the number of times they have been built in that source dir
-	@echo "* Incrementing build number for next build"
-	@bash -c 'read major minor release build reponame < Version.string; \
-	   let build=build+1; \
-	   echo "$$major $$minor $$release $$build $$reponame" > Version.string; \
-	 '
 
 Server.o: Server.c Server.h Global.h Version.h
 	${DEF_CC_CMD} -c Server.c
@@ -49,25 +47,8 @@ ImageLoader.o: ImageLoader.h ImageLoader.c ParseGL.h Global.h
 Version.o: Version.autogen.c
 	${DEF_CC_CMD} -c Version.autogen.c -o Version.o
 
-Version.string: Version.log
-	@echo "-> Regenerating Version.string from Version.log"
-	@tail -n 1 Version.log | sed -n 's/\(^[^:]*\).*/\1/p' | bash -c ' \
-	   read major minor release; \
-	   let major=major+0 minor=minor+0 release=release+0; \
-	   if [ -f _darcs/RepoName ]; then cur_repo="$$(cat _darcs/RepoName)"; else cur_repo="$$(hostname)"; fi; \
-	   echo $$major $$minor $$release 0 $$cur_repo > Version.string; \
-	 '
-
-Version.autogen.c: Version.string
-	@echo "-> Regenerating Version.c from Version.string"
-	@( read major minor release build reponame < Version.string; \
-	   echo "const int CGLVER_Major=$$major;"; \
-	   echo "const int CGLVER_Minor=$$minor;"; \
-	   echo "const int CGLVER_Release=$$release;"; \
-	   echo "const int CGLVER_Build=$$build;"; \
-	   echo "const char* CGLVER_RepoName=\"$$reponame\";"; \
-	   echo "const char* CGLVER_String=\"$$major.$$minor.$$release.$$reponame[$$build]\";"; \
-	 ) > Version.autogen.c
+Version.autogen.c Version.parts:
+	./build-version.sh
 
 Global.o: Global.c Global.h
 	${DEF_CC_CMD} -c Global.c
@@ -94,12 +75,12 @@ IntConstHash.autogen.c: HashTableGenUtil ConstList.txt Makefile ${ALL_HEADERS}
 	   echo "#include \"GlHeaders.h\"";\
 	   echo "#include \"SymbolHash.h\"";\
 	   for hFile in `grep -l "#define CGL_" ${ALL_HEADERS}`; do \
-		 echo "#include \"$$hFile\"";\
+	      echo "#include \"$$hFile\"";\
 	   done;\
 	   ( cat ConstList.txt;\
-		 grep -h "#define CGL_" ${ALL_HEADERS} | sed 's/#define \(CGL_[^ ]*\).*/\1/'; \
+	     grep -h "#define CGL_" ${ALL_HEADERS} | sed 's/#define \(CGL_[^ ]*\).*/\1/'; \
 	   ) | sed 's/\(.*\)/\1 (int)(\1)/' \
-		| ./HashTableGenUtil 1024 IntConstLookup IB IntConstHashEntry;\
+	     | ./HashTableGenUtil 1024 IntConstLookup IB IntConstHashEntry;\
 	 ) >IntConstHash.autogen.c
 
 CmdHash.autogen.o: CmdHash.autogen.c Global.h
@@ -110,7 +91,7 @@ CmdHash.autogen.c: HashTableGenUtil Makefile ${ALL_HEADERS}
 	@( echo "// This code automatically generated by makefile.  Do not modify.";\
 	   echo "#include \"Global.h\"";\
 	   for hFile in `grep -l PUBLISHED ${ALL_HEADERS}`; do \
-		 echo "#include \"$$hFile\"";\
+	     echo "#include \"$$hFile\"";\
 	   done;\
 	   sed -n '/^PUBLISHED(\([^,]*\),\([^)]*\)).*/s//\1 \2/p' *.h \
  	    | ./HashTableGenUtil 64 CmdLookup CB CmdHashEntry;\
@@ -144,37 +125,21 @@ ConstList.txt:
 	@echo
 
 install: bin/CmdlineGL
-	if [ ! -d @bindir@ ]; then install -d @bindir@; fi
-	
+	if [ ! -d @bindir@ ]; then install -d @bindir@; fi	
 	install bin/CmdlineGL @bindir@
-	@if [ -n "${INSTALL_SHELL_BINDINGS}" ]; then \
-		echo "-> Making all the symlinks from the CmdlineGLClient script to the command names in bin" \
-		&& echo install CmdlineGLClient @bindir@ \
-		&& install CmdlineGLClient @bindir@ \
-		&& sed -n '/^PUBLISHED(\([^,]*\),.*/s//\1/p' *.h \
-		 | while read fn; do \
-		 	echo "ln -sf CmdlineGLClient @bindir@/$$fn";\
-		 	ln -s CmdlineGLClient @bindir@/$$fn;\
- 		   done \
-	fi
 
-dist: Version.string bin/CmdlineGL
-	@echo "==>> Make sure to update the Version.log to increment the release number! <<=="
-	@( read major minor release andstuff < Version.string; \
-	   DistName="CmdlineGL_$$major.$$minor.$$release"; \
-	   echo "Generating dist tarball using 'darcs dist'"; \
-	   darcs dist -d "$$DistName"; \
-	   echo "Refreshing configure script"; \
-	   autoconf; \
-	   echo "Adding 'configure' script to tarball"; \
-	   [[ -d "$$DistName" ]] || mkdir "$$DistName"; \
-	   cp configure "$$DistName/configure"; \
-	   gunzip "$$DistName.tar.gz"; \
-	   tar -rf "$$DistName.tar" "$$DistName/configure"; \
-	   gzip "$$DistName.tar"; \
-	   rm "$$DistName/configure"; \
-	   rmdir "$$DistName"; \
-	   echo "Release tarball is $$DistName.tar.gz"; \
+dist: bin/CmdlineGL
+	@echo "Note: Update Changes and git tag to change version"
+	@( read major minor release andstuff < Version.parts; \
+	   DistName="CmdlineGL-$$major.$$minor.$$release";
+	   if [ -n "$andstuff" ]; then echo "Warning: unofficial release"; DistName="$DistName-$andstuff"; fi; \
+	   echo "Generating clean dist"; \
+	   [ -d "$DistName" ] && { echo "Error: directory $$DistName already exists"; exit 1; }; \
+	   git --work-dir="$$DistName" checkout . \
+	   && echo "Including configure script and generated files" \
+	   && autoheader && autoconf && cp config.h.in configure "$$DistName/" \
+	   && bzip2 "$$DistName.tar.bz2" "$$DistName" \
+	   && echo "Release tarball is $$DistName.tar.bz2"; \
 	)
 
 clean:
@@ -183,3 +148,9 @@ clean:
 	rm -f ConstList.txt
 	rm -rf bin/
 	rm -f HashTableGenUtil
+
+distclean: clean
+	rm configure config.status config.log
+	rm -r autom4te.cache
+	rm config.h config.h.in
+	rm Makefile
